{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/galenit_coresdk\/authenticationui\/fail"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK\/AuthenticationUI\/fail","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specifies that the error"},{"type":"text","text":" "},{"type":"text","text":"errSecInteractionNotAllowed will be returned if an item needs"},{"type":"text","text":" "},{"type":"text","text":"to authenticate with UI"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"}],"title":"AuthenticationUI.fail","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:15GalenIT_CoreSDK16AuthenticationUIO4failyA2CmF","modules":[{"name":"GalenIT_CoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK","doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK\/AuthenticationUI"]]},"references":{"doc://com.galenit.GalenIT-CoreSDK/documentation/GalenIT_CoreSDK/AuthenticationUI":{"role":"symbol","title":"AuthenticationUI","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationUI"}],"abstract":[{"type":"text","text":"Predefined item attribute constants used to get or set values"},{"type":"text","text":" "},{"type":"text","text":"in a dictionary. The kSecUseAuthenticationUI constant is the key and its"},{"type":"text","text":" "},{"type":"text","text":"value is one of the constants defined here."},{"type":"text","text":" "},{"type":"text","text":"If the key kSecUseAuthenticationUI not provided then kSecUseAuthenticationUIAllow"},{"type":"text","text":" "},{"type":"text","text":"is used as default."}],"identifier":"doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK\/AuthenticationUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationUI"}],"url":"\/documentation\/galenit_coresdk\/authenticationui"},"doc://com.galenit.GalenIT-CoreSDK/documentation/GalenIT_CoreSDK":{"role":"collection","title":"GalenIT_CoreSDK","abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/galenit_coresdk"},"doc://com.galenit.GalenIT-CoreSDK/documentation/GalenIT_CoreSDK/AuthenticationUI/fail":{"role":"symbol","title":"AuthenticationUI.fail","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"}],"abstract":[{"type":"text","text":"Specifies that the error"},{"type":"text","text":" "},{"type":"text","text":"errSecInteractionNotAllowed will be returned if an item needs"},{"type":"text","text":" "},{"type":"text","text":"to authenticate with UI"}],"identifier":"doc:\/\/com.galenit.GalenIT-CoreSDK\/documentation\/GalenIT_CoreSDK\/AuthenticationUI\/fail","kind":"symbol","type":"topic","url":"\/documentation\/galenit_coresdk\/authenticationui\/fail"}}}